/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "soma.h"


void
soma_programa_2(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	soma  calcula_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, soma_programa, soma_programa, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("Digite o valor A: ");
	scanf("%f", &calcula_2_arg.a);
	printf("Digite o valor B: ");
	scanf("%f", &calcula_2_arg.b);

	result_1 = calcula_2(&calcula_2_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("O valor da soma eh: %f\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	soma_programa_2 (host);
exit (0);
}
