/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SOMA_H_RPCGEN
#define _SOMA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct soma {
	float a;
	float b;
};
typedef struct soma soma;

#define soma_programa 3
//#define soma_programa 2

#if defined(__STDC__) || defined(__cplusplus)
#define calcula 1
extern  float * calcula_2(soma *, CLIENT *);
extern  float * calcula_2_svc(soma *, struct svc_req *);
extern int soma_programa_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define calcula 1
extern  float * calcula_2();
extern  float * calcula_2_svc();
extern int soma_programa_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_soma (XDR *, soma*);

#else /* K&R C */
extern bool_t xdr_soma ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SOMA_H_RPCGEN */
