/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "soma.h"

float *
calcula_2_svc(soma *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("O cliente requisitou um procedimento remoto: %f\n", argp->a);
	printf("O cliente requisitou um procedimento remoto: %f\n", argp->b);
	
	result = argp->a + argp->b;
	
	printf("A soma de A e B eh: %f\n", result);

	return &result;
}
